### ISSUE TITLE
Adding DKIM signature raises TXT record too long

### ISSUE THREAD

**Issue by Ashiq5** [paulc/dnslib#34]
If I want to add a DKIM signature as a RR for a domain, it raises the following stack trace. In BIND/ NSD, one can separate the TXT record in quotes to accommodate this case. But what's the workaround for this in dnslib?

```
Traceback (most recent call last):
  File "ddns.py", line 56, in <module>
    D._domainkey.mail: [TXT(DKIM)],
  File "python3.8/site-packages/dnslib/dns.py", line 1114, in __init__
    raise DNSError("TXT record too long: %s" % self.data)
```

**Comment by Ashiq5** [comment]
Most likely passing an array of strings to the TXT record constructor solves this issue.
